// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosEventComm::PullSupplier_pull_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosEventCommPullSupplierPullOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventCommPullSupplierPullOutId_Const = "IDL:CosEventComm/PullSupplier_pull_Out:1.0"

func (self *CosEventCommPullSupplierPullOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommPullSupplierPullOut) GoString() string {
	return self.String()
}

func (self *CosEventCommPullSupplierPullOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullSupplierPullOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullSupplierPullOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommPullSupplierPullOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPullSupplierPullOutHelper = CosEventCommPullSupplierPullOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommPullSupplierPullOutId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommPullSupplierPullOut.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommPullSupplierPullOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommPullSupplierPullOut{}
			},
			__reflect__.TypeOf((*CosEventCommPullSupplierPullOut)(nil))))
}
