// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosEventComm::PullSupplier_disconnect_pull_supplier_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosEventCommPullSupplierDisconnectPullSupplierOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventCommPullSupplierDisconnectPullSupplierOutId_Const = "IDL:CosEventComm/PullSupplier_disconnect_pull_supplier_Out:1.0"

func (self *CosEventCommPullSupplierDisconnectPullSupplierOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommPullSupplierDisconnectPullSupplierOut) GoString() string {
	return self.String()
}

func (self *CosEventCommPullSupplierDisconnectPullSupplierOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullSupplierDisconnectPullSupplierOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullSupplierDisconnectPullSupplierOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommPullSupplierDisconnectPullSupplierOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPullSupplierDisconnectPullSupplierOutHelper = CosEventCommPullSupplierDisconnectPullSupplierOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommPullSupplierDisconnectPullSupplierOutId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommPullSupplierDisconnectPullSupplierOut.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommPullSupplierDisconnectPullSupplierOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommPullSupplierDisconnectPullSupplierOut{}
			},
			__reflect__.TypeOf((*CosEventCommPullSupplierDisconnectPullSupplierOut)(nil))))
}
