// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosEventComm::PushConsumer_push_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosEventCommPushConsumerPushIn struct {
	__goidl__.IdlObject
	Data __goidl__.IdlAny `json:"Data"`
}

//noinspection GoSnakeCaseUsage
const CosEventCommPushConsumerPushInId_Const = "IDL:CosEventComm/PushConsumer_push_In:1.0"

func (self *CosEventCommPushConsumerPushIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommPushConsumerPushIn) GoString() string {
	return self.String()
}

func (self *CosEventCommPushConsumerPushIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(AnyType)
	self.Data, err = __goidl__.IdlAnyHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPushConsumerPushIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPushConsumerPushIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(AnyType)
	err = __goidl__.IdlAnyHelper.Write(stream, self.Data)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommPushConsumerPushIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPushConsumerPushInHelper = CosEventCommPushConsumerPushIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommPushConsumerPushInId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommPushConsumerPushIn.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommPushConsumerPushIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommPushConsumerPushIn{}
			},
			__reflect__.TypeOf((*CosEventCommPushConsumerPushIn)(nil))))
}
