// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosEventComm::PushSupplier_disconnect_push_supplier_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosEventCommPushSupplierDisconnectPushSupplierOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventCommPushSupplierDisconnectPushSupplierOutId_Const = "IDL:CosEventComm/PushSupplier_disconnect_push_supplier_Out:1.0"

func (self *CosEventCommPushSupplierDisconnectPushSupplierOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommPushSupplierDisconnectPushSupplierOut) GoString() string {
	return self.String()
}

func (self *CosEventCommPushSupplierDisconnectPushSupplierOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPushSupplierDisconnectPushSupplierOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPushSupplierDisconnectPushSupplierOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommPushSupplierDisconnectPushSupplierOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPushSupplierDisconnectPushSupplierOutHelper = CosEventCommPushSupplierDisconnectPushSupplierOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommPushSupplierDisconnectPushSupplierOutId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommPushSupplierDisconnectPushSupplierOut.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommPushSupplierDisconnectPushSupplierOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommPushSupplierDisconnectPushSupplierOut{}
			},
			__reflect__.TypeOf((*CosEventCommPushSupplierDisconnectPushSupplierOut)(nil))))
}
