// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CosEventComm::PushSupplier", generatedBy by: "WriteInterface"
type CosEventCommPushSupplier interface {
	// Original name: "disconnect_push_supplier"
	DisconnectPushSupplier(params CosEventCommPushSupplierDisconnectPushSupplierIn) (CosEventCommPushSupplierDisconnectPushSupplierOut, error)
}

const CosEventCommPushSupplierDisconnectPushSupplierOperation = "disconnect_push_supplier"
//noinspection GoSnakeCaseUsage
type CosEventCommPushSupplier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosEventCommPushSupplierId_Const = "IDL:omg.org/CosEventComm/PushSupplier:1.0"

func (self CosEventCommPushSupplier_Helper) Id() string {
	return CosEventCommPushSupplierId_Const
}

func (self CosEventCommPushSupplier_Helper) Read(stream __goidl__.IReadAny) (CosEventCommPushSupplier, error) {
	return nil, nil
}

func (self CosEventCommPushSupplier_Helper) Write(stream __goidl__.IWriteAny, v CosEventCommPushSupplier) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPushSupplierHelper = CosEventCommPushSupplier_Helper{}

func init() {
}
