// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CosEventComm::PullConsumer", generatedBy by: "WriteInterface"
type CosEventCommPullConsumer interface {
	// Original name: "disconnect_pull_consumer"
	DisconnectPullConsumer(params CosEventCommPullConsumerDisconnectPullConsumerIn) (CosEventCommPullConsumerDisconnectPullConsumerOut, error)
}

const CosEventCommPullConsumerDisconnectPullConsumerOperation = "disconnect_pull_consumer"
//noinspection GoSnakeCaseUsage
type CosEventCommPullConsumer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosEventCommPullConsumerId_Const = "IDL:omg.org/CosEventComm/PullConsumer:1.0"

func (self CosEventCommPullConsumer_Helper) Id() string {
	return CosEventCommPullConsumerId_Const
}

func (self CosEventCommPullConsumer_Helper) Read(stream __goidl__.IReadAny) (CosEventCommPullConsumer, error) {
	return nil, nil
}

func (self CosEventCommPullConsumer_Helper) Write(stream __goidl__.IWriteAny, v CosEventCommPullConsumer) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPullConsumerHelper = CosEventCommPullConsumer_Helper{}

func init() {
}
