// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

// Struct declaration: "CosEventComm::PullSupplier_Stub", generatedBy by: "WriteStructDcl"
type CosEventCommPullSupplierStub struct {
}


func init() {
}
