// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosEventComm::PullConsumer_disconnect_pull_consumer_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosEventCommPullConsumerDisconnectPullConsumerIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventCommPullConsumerDisconnectPullConsumerInId_Const = "IDL:CosEventComm/PullConsumer_disconnect_pull_consumer_In:1.0"

func (self *CosEventCommPullConsumerDisconnectPullConsumerIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommPullConsumerDisconnectPullConsumerIn) GoString() string {
	return self.String()
}

func (self *CosEventCommPullConsumerDisconnectPullConsumerIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullConsumerDisconnectPullConsumerIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullConsumerDisconnectPullConsumerIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommPullConsumerDisconnectPullConsumerIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPullConsumerDisconnectPullConsumerInHelper = CosEventCommPullConsumerDisconnectPullConsumerIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommPullConsumerDisconnectPullConsumerInId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommPullConsumerDisconnectPullConsumerIn.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommPullConsumerDisconnectPullConsumerIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommPullConsumerDisconnectPullConsumerIn{}
			},
			__reflect__.TypeOf((*CosEventCommPullConsumerDisconnectPullConsumerIn)(nil))))
}
