// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

// Struct declaration: "CosEventComm::PushConsumer_Stub", generatedBy by: "WriteStructDcl"
type CosEventCommPushConsumerStub struct {
}


func init() {
}
