// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

// Struct declaration: "CosEventComm::PullConsumer_Stub", generatedBy by: "WriteStructDcl"
type CosEventCommPullConsumerStub struct {
}


func init() {
}
