// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosEventComm::PushConsumer_push_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosEventCommPushConsumerPushOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventCommPushConsumerPushOutId_Const = "IDL:CosEventComm/PushConsumer_push_Out:1.0"

func (self *CosEventCommPushConsumerPushOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommPushConsumerPushOut) GoString() string {
	return self.String()
}

func (self *CosEventCommPushConsumerPushOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPushConsumerPushOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPushConsumerPushOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommPushConsumerPushOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPushConsumerPushOutHelper = CosEventCommPushConsumerPushOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommPushConsumerPushOutId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommPushConsumerPushOut.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommPushConsumerPushOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommPushConsumerPushOut{}
			},
			__reflect__.TypeOf((*CosEventCommPushConsumerPushOut)(nil))))
}
