// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosEventComm::PushSupplier_disconnect_push_supplier_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosEventCommPushSupplierDisconnectPushSupplierIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventCommPushSupplierDisconnectPushSupplierInId_Const = "IDL:CosEventComm/PushSupplier_disconnect_push_supplier_In:1.0"

func (self *CosEventCommPushSupplierDisconnectPushSupplierIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommPushSupplierDisconnectPushSupplierIn) GoString() string {
	return self.String()
}

func (self *CosEventCommPushSupplierDisconnectPushSupplierIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPushSupplierDisconnectPushSupplierIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPushSupplierDisconnectPushSupplierIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommPushSupplierDisconnectPushSupplierIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPushSupplierDisconnectPushSupplierInHelper = CosEventCommPushSupplierDisconnectPushSupplierIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommPushSupplierDisconnectPushSupplierInId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommPushSupplierDisconnectPushSupplierIn.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommPushSupplierDisconnectPushSupplierIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommPushSupplierDisconnectPushSupplierIn{}
			},
			__reflect__.TypeOf((*CosEventCommPushSupplierDisconnectPushSupplierIn)(nil))))
}
