// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosEventComm::PullSupplier_disconnect_pull_supplier_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosEventCommPullSupplierDisconnectPullSupplierIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventCommPullSupplierDisconnectPullSupplierInId_Const = "IDL:CosEventComm/PullSupplier_disconnect_pull_supplier_In:1.0"

func (self *CosEventCommPullSupplierDisconnectPullSupplierIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommPullSupplierDisconnectPullSupplierIn) GoString() string {
	return self.String()
}

func (self *CosEventCommPullSupplierDisconnectPullSupplierIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullSupplierDisconnectPullSupplierIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullSupplierDisconnectPullSupplierIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommPullSupplierDisconnectPullSupplierIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPullSupplierDisconnectPullSupplierInHelper = CosEventCommPullSupplierDisconnectPullSupplierIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommPullSupplierDisconnectPullSupplierInId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommPullSupplierDisconnectPullSupplierIn.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommPullSupplierDisconnectPullSupplierIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommPullSupplierDisconnectPullSupplierIn{}
			},
			__reflect__.TypeOf((*CosEventCommPullSupplierDisconnectPullSupplierIn)(nil))))
}
