// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

// Struct declaration: "CosEventComm::PushSupplier_Stub", generatedBy by: "WriteStructDcl"
type CosEventCommPushSupplierStub struct {
}


func init() {
}
