// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosEventComm::PullConsumer_disconnect_pull_consumer_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosEventCommPullConsumerDisconnectPullConsumerOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventCommPullConsumerDisconnectPullConsumerOutId_Const = "IDL:CosEventComm/PullConsumer_disconnect_pull_consumer_Out:1.0"

func (self *CosEventCommPullConsumerDisconnectPullConsumerOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommPullConsumerDisconnectPullConsumerOut) GoString() string {
	return self.String()
}

func (self *CosEventCommPullConsumerDisconnectPullConsumerOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullConsumerDisconnectPullConsumerOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommPullConsumerDisconnectPullConsumerOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommPullConsumerDisconnectPullConsumerOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommPullConsumerDisconnectPullConsumerOutHelper = CosEventCommPullConsumerDisconnectPullConsumerOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommPullConsumerDisconnectPullConsumerOutId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommPullConsumerDisconnectPullConsumerOut.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommPullConsumerDisconnectPullConsumerOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommPullConsumerDisconnectPullConsumerOut{}
			},
			__reflect__.TypeOf((*CosEventCommPullConsumerDisconnectPullConsumerOut)(nil))))
}
