// Code generated by me. DO NOT EDIT.

package goIdlCosEventComm

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Exception declaration: "CosEventComm::Disconnected", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CosEventCommDisconnected struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosEventCommDisconnectedId_Const = "IDL:omg.org/CosEventComm/Disconnected:1.0"

func (self *CosEventCommDisconnected) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosEventCommDisconnected) Error() string{
	return 	__fmt__.Sprintf("Error of type CosEventCommDisconnected(%v)", self.String())
}
func (self *CosEventCommDisconnected) GoString() string {
	return self.String()
}

func (self *CosEventCommDisconnected) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommDisconnected) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosEventCommDisconnected) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosEventCommDisconnected_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosEventCommDisconnectedHelper = CosEventCommDisconnected_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosEventCommDisconnectedId_Const,
			__goidl__.StructType,
			"CosEventComm.idl",
			"xdl_CosEventCommDisconnected.go",
			func() __goidl__.IIdlObject {
				return &CosEventCommDisconnected{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosEventCommDisconnected{}
			},
			__reflect__.TypeOf((*CosEventCommDisconnected)(nil))))
}
